spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/my_data}
    username: my_data
    password: my_data
logging:
  level:
    com.mydata: DEBUG
